### ISSUE TITLE
One of referenced outputs is already spent

### ISSUE THREAD

**Issue by pavlowd** [bcndev/bytecoin#85]
Hi, I am build pool for testnet and testnet on 
http://amsterdam.bytecoins.world:8085/

Now I have problems with pool payments, because of 

> Json Error sending transaction from payment queue conflict height=2543 code=-103 msg=One of referenced outputs is already spent

error in walletd-verbose.log  .

Looks like **get_random_outputs** generate identical outputs sometimes (with the same global_index), for different transactions.
Then one transaction executes and going to mempool, and other stuck on payment queue with that error - because that output is already spent.

![screenshot_2](https://user-images.githubusercontent.com/5560785/44336392-fac7cc80-a47f-11e8-84bd-6da2dbc54423.jpg)

I am right or it's mistake somewhere on my side ?
How to fix it ?
It's strange that other pools haven't that problem.

Currently pool makes 6 successful transactions , but only one is executed.

**Comment by mounirrquiba** [comment]
Hi @virgeny 
Same issue on bytecoin-pool.org,
Fixed with this into lib/paymentProcessor.js

```
for (var worker in payments){
    var amount = parseInt(payments[worker]);
	if(config.payments.maxTransactionAmount && amount + commandAmount > config.payments.maxTransactionAmount) {
        amount = config.payments.maxTransactionAmount - commandAmount;
    }

	if(!transferCommands[commandIndex]) {
		transferCommands[commandIndex] = {
			redis: [],
			amount : 0,
			rpc: {
                             transaction: {
                                 anonymity: config.payments.mixin,
                                 payment_id: "",
                                 transfers: []
                             },
                             spend_addresses: [
                                config.poolServer.poolAddress
                             ],
                             change_address: config.poolServer.poolAddress,
                             optimization: "minimal"
                        }  
		};
	}

    transferCommands[commandIndex].rpc.transaction.transfers.push({amount: amount, address: worker});
    transferCommands[commandIndex].redis.push(['hincrby', config.coin + ':workers:' + worker, 'balance', -amount]);
    transferCommands[commandIndex].redis.push(['hincrby', config.coin + ':workers:' + worker, 'paid', amount]);
    transferCommands[commandIndex].amount += amount;

    addresses++;
    commandAmount += amount;
    if (addresses >= config.payments.maxAddresses || ( config.payments.maxTransactionAmount && commandAmount >= config.payments.maxTransactionAmount)) {
        continue; // <------ FIX HERE
        commandIndex++;
        addresses = 0;
        commandAmount = 0;
    }
}
```

Happy Mining 👍

**Comment by mounirrquiba** [comment]
@nilhcraiv isn't the solution, is just a hot fix, solution from daemon not from pool code.

**Comment by nilhcraiv** [comment]
Yes @mounirrquiba besides in the destination account the amount appears blocked, that is, it’s like a normal transaction but those coins are stuck...

**Comment by nilhcraiv** [comment]
Do you know if this has been resolved in the last update? my pool can not make payments at the same time... I’m using the @mounirrquiba solution :/

**Comment by nilhcraiv** [comment]
**This error continues**, you launch new updates but this is not fixed. This causes transfers that never arrive, you have to solve it as soon as possible.
